### ISSUE TITLE
Make it impossible to increase the window size

### ISSUE THREAD

**Issue by marcinjahn** [KelvinNovais/Kasasa#11]
I think it doesn't give any value to increase the window size beyond the image size. Once you do that, it's difficult to go back to the "perfect" proportions that are the image proportions.

**Comment by KelvinNovais** [comment]
GTK4 doesn't allow to set a max size or a resizing ratio for a window.

A possible solution could be letting the user to define a desired max window size; in this way, when a new window is being created, its size will be calculated based on that user choice. 

_(Final)_ result: the window has a max size, will obey the picture proportions, and won't be resizable.

**Comment by KelvinNovais** [comment]
Hey there! Just willing a feedback about the "occupying screen percentage", implemented on commit 033c545def4ec02d8cfdf9f206e79eaa51c1cb10

> A possible solution could be letting the user to define a desired max window size

Differently from what I said, it doesn't set a width and a height, but a percentage instead. It gives the window more freedom on its size, as long as it respects that percentage of screen
