### ISSUE TITLE
[Suggestion] Option to hide error message if screenshot is cancelled

### ISSUE THREAD

**Issue by BakiDance** [KelvinNovais/Kasasa#15]
This app is incredible. It completely solves a major issue I had with taking screenshots in Gnome, however I do have one minor gripe with Kasasa: When I take a screenshot, but decide to cancel it by hitting ESC, Kasasa complains that the screenshot failed and to check that it has permission.

Obviously, this is a good error message to display to users so they know how to set up Kasasa properly, but once it already is set up, it becomes a bit of an annoyance. 

I take screenshots a lot as I game, and sometimes (if the moment isn't right), I'll hit ESC to cancel the screenshot so I can try again. Except, now that I'm using Kasasa, doing so means that a dialog window will appear over my content that I have to close first. Sometimes this means that I'll either miss the moment, or take a screenshot that includes a "Screenshot failed" window, haha.

I'd love it if there were just a way to hide this error altogether if a screenshot is canceled or fails for any other reason, and to only show a window upon a successful caption. Perhaps a toggle in Kasasa's settings?

**Comment by KelvinNovais** [comment]
> Perhaps a toggle in Kasasa's settings?

Maybe an option to emit the error as a notification, or opening the window as Kasasa currently does, or just defaulting to the first one.

In any case, hiding an error isn't the best option; the good thing about using a notification is that it can be omitted when "Do not disturb" is enabled.

**Comment by BakiDance** [comment]
Ideally, it would be nice if there were a way to prevent Kasasa from opening a window at all if a screenshot was cancelled. A notification, instead, would be an improvement. My main gripe with the window opening at all is that it gets in the way of me taking another screenshot while gaming.

**Comment by BakiDance** [comment]
For example, this is what I mean. I accidentally hit ESC to back out of the screenshot (hoping to capture something a little bit later), but the error window appeared causing me to miss the thing I was actually trying to capture. ![image](https://github.com/user-attachments/assets/3dcb72d9-2925-4fee-907b-594f482f568e)

**Comment by KelvinNovais** [comment]
Kasasa will use a system notification if the screenshot fails the first time opening the app (0dfc57e73b927e33470860404d2fc3b63e846c82). This new version will be release soon.

Unfortunately the returned error by the Portal API does not specify if the screenshot has been canceled. Otherwise, it could completely avoid emitting a notification for this case.
