### ISSUE TITLE
[Feature Request] Make whole window a drag target

### ISSUE THREAD

**Issue by u1f98e** [KelvinNovais/Kasasa#9]
I've found myself trying to move the screenshot window around by dragging in the screenshot area (similar to flameshot's pin feature). Making the whole window draggable would make it easier to manipulate.

I'd be willing to make a PR for this, but wanted to check to see if there were any different future plans for interacting with the screenshot that might conflict with this feature.

**Comment by KelvinNovais** [comment]
This feature was added on commit fed431a7d013003af6276bb6fe7a0a016208da5e
It will be available on next release
